name: Update Swift Package and Documentation
on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  update_swift_package:
    name: Update Swift Package
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update package
        id: update_package
        run: |
          echo "::group::determining release tag"
          ref=${{ github.ref }} 
          release_tag="${ref##*refs/tags/}" 
          echo "tag=$release_tag" >> "$GITHUB_ENV"
          echo $release_tag
          echo "::endgroup::"
          
          echo "::group::update_package.sh"
          sh ./update_package.sh $release_tag AdSDKCore "AdSDKCore-$release_tag.zip" AdSDKSwiftUI "AdSDKSwiftUI-$release_tag.zip"
          echo "::endgroup::"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: swift package deployer
          author_email: mail@example.com
          message: 'Updated swift package definition'
          add: 'Package.swift'
          tag: ${{ env.tag }} --force
          push: origin HEAD:main
          tag_push: --force
  deploy_docs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    needs: update_swift_package
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get docs artifact
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: "docs.zip"
          token: ${{ secrets.GH_TOKEN }}
      - name: Switch to gh_pages branch
        run: |
          git config --global user.email "mail@example.com"
          git config --global user.name "documentation deployer"
          git fetch origin gh_pages:gh_pages
          git checkout gh_pages
          git pull --rebase origin gh_pages
      - name: Update docs folder
        run: |
          rm -r docs
          unzip docs.zip -d ./
          rm docs.zip
      - name: Commit and push changes to gh_pages
        run: |
          git add docs
          git commit -m "Update docs"
          git push -u origin gh_pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}